
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: visualbi.east-us-2.azure
      user: POOVARASANB
      password: Bpp=86005
      database: RAW
      schema: sap
      role : FIVETRAN_ROLE
      warehouse : DEMO_WH
      threads: 1
      client_session_keep_alive: False
